name: Compile the bot and build the docker image

on:
  push:
    branches:
    - main
    - ci
  pull_request:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get

      - name: Build
        run: go build -o texas_bot -v .

      - name: Test
        run: go test -v .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: texas_bot
          path: ./texas_bot
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: ./texas_bot

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        name: Check out the repository
      - uses: actions/download-artifact@v3
        name: Download the Build Artifact
        with:
          name: texas_bot
          path: ./texas_bot
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}/texas_bot
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}